image: maven:3-jdk-8

build:
  script: "mvn install -B"
  
stages:
- build
- deploy

build_job:
  stage: build
  script:
  - mvn clean package
  only:
  - master
  
deploy_job:
  stage: deploy
  script:
  - mvn clean package deploy:deploy-file -DpomFile=pom.xml -Durl=https://mymavenrepo.com/repo/N3WVdAIetPqMO0ZH6X5e/devint/ -DrepositoryId=devint -Dfile=target/devint-engine-1.1-SNAPSHOT.jar
  only:
  - release